"""g

Revision ID: 049071604948
Revises: e2ac55abfe32
Create Date: 2024-06-18 11:42:45.877446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '049071604948'
down_revision: Union[str, None] = 'e2ac55abfe32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(length=900),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=900),
               existing_nullable=False)
    # ### end Alembic commands ###
