"""new_data

Revision ID: 0a6f52415d4a
Revises: b75c4ead0335
Create Date: 2024-06-19 16:22:31.178358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a6f52415d4a'
down_revision: Union[str, None] = 'b75c4ead0335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('followers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('following', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'following')
    op.drop_column('users', 'followers')
    # ### end Alembic commands ###
