"""y

Revision ID: 57bbf89e8e8e
Revises: 049071604948
Create Date: 2024-06-18 17:11:41.933302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57bbf89e8e8e'
down_revision: Union[str, None] = '049071604948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
