"""add_ratting_system

Revision ID: 666dab9be831
Revises: 565e8a0ce996
Create Date: 2024-06-27 16:23:09.673324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666dab9be831'
down_revision: Union[str, None] = '565e8a0ce996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('ratings_count', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('total_rating', sa.Float(), nullable=True))
    op.add_column('blogs', sa.Column('average_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'average_rating')
    op.drop_column('blogs', 'total_rating')
    op.drop_column('blogs', 'ratings_count')
    # ### end Alembic commands ###
