"""o

Revision ID: a4594ec7baf6
Revises: dea99e811d20
Create Date: 2024-06-18 17:38:39.091412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4594ec7baf6'
down_revision: Union[str, None] = 'dea99e811d20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
