"""g

Revision ID: e2ac55abfe32
Revises: f3b84bf844ea
Create Date: 2024-06-18 11:39:26.793269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ac55abfe32'
down_revision: Union[str, None] = 'f3b84bf844ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(length=900),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blogs', 'content',
               existing_type=sa.String(length=900),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
